#!/usr/bin/env node
// Generates the method-count line in README.md from schema/meta.json.
// Usage:
//   node scripts/method-counts.mjs          # rewrite README between the markers
//   node scripts/method-counts.mjs --check   # exit 1 if README is stale (for CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const meta = JSON.parse(readFileSync(join(root, 'schema/meta.json'), 'utf8'));
const readmePath = join(root, 'README.md');

const methods = Object.values(meta.methods);
const byTier = (t) => methods.filter((m) => m.tier === t).length;
const byStab = (s) => methods.filter((m) => m.stability === s).length;

const line =
  `The protocol currently defines **${methods.length} methods** across three tiers: ` +
  `**${byTier('core')} core**, **${byTier('structure')} structure**, **${byTier('extension')} extension**. ` +
  `By stability label: **${byStab('stable')} stable**, **${byStab('staging')} staging**.`;

const START = '<!-- METHOD-COUNTS:START (generated by scripts/method-counts.mjs — do not edit by hand) -->';
const END = '<!-- METHOD-COUNTS:END -->';
const block = `${START}\n${line}\n${END}`;

const readme = readFileSync(readmePath, 'utf8');
const re = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`);
if (!re.test(readme)) {
  console.error('method-counts: markers not found in README.md');
  process.exit(2);
}
const updated = readme.replace(re, block);

if (process.argv.includes('--check')) {
  if (updated !== readme) {
    console.error('method-counts: README is stale. Run `node scripts/method-counts.mjs`.');
    process.exit(1);
  }
  console.log('method-counts: README is up to date.');
} else {
  writeFileSync(readmePath, updated);
  console.log('method-counts: README updated.\n' + line.replace(/\*\*/g, ''));
}
