#!/usr/bin/env node
// Splits schema/meta.json into schema/core/meta.json + schema/ext/<name>/manifest.json
// per docs/map-ext.md. Run once; thereafter schema/meta.json is GENERATED by build-meta.mjs.
//
// Routing is by method prefix (longest match wins); anything unmatched is core.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const meta = JSON.parse(readFileSync(join(root, 'schema/meta.json'), 'utf8'));

// Extension descriptors (from docs/registry.md). errorGroups = error-code group keys this ext owns.
const EXT = {
  sessions:    { uri: 'urn:map:ext:sessions:1',    stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'map/session/',    errorRange: [16000, 16999], errorGroups: [] },
  mail:        { uri: 'urn:map:ext:mail:1',        stability: 'stable',  owner: 'agent-inbox',          methodPrefix: 'mail/',           errorRange: [10000, 10999], errorGroups: ['mail'] },
  trajectory:  { uri: 'urn:map:ext:trajectory:1',  stability: 'stable',  owner: 'multi-agent-protocol', methodPrefix: 'trajectory/',     errorRange: [13000, 13999], errorGroups: ['trajectory'] },
  tasks:       { uri: 'urn:map:ext:tasks:1',       stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'map/tasks/',      errorRange: [14000, 14999], errorGroups: ['tasks'] },
  workspace:   { uri: 'urn:map:ext:workspace:1',   stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'workspace/',      errorRange: [12000, 12999], errorGroups: ['workspace'] },
  credentials: { uri: 'urn:map:ext:credentials:1', stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'cred/',           errorRange: [11000, 11999], errorGroups: ['credentials'] },
  resources:   { uri: 'urn:map:ext:resources:1',   stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'map/resources/',  errorRange: [15000, 15999], errorGroups: [] },
  federation:  { uri: 'urn:map:ext:federation:1',  stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'map/federation/', errorRange: [5000, 5999],   errorGroups: ['federation'] },
  steering:    { uri: 'urn:map:ext:steering:1',    stability: 'staging', owner: 'multi-agent-protocol', methodPrefix: 'map/inject',      errorRange: null,           errorGroups: [] },
};
const CORE_ERROR_GROUPS = ['protocol', 'auth', 'routing', 'agent', 'resource'];

// Longest-prefix router: returns ext name or 'core'.
function routeMethod(name) {
  let best = null, bestLen = -1;
  for (const [ext, d] of Object.entries(EXT)) {
    if (name.startsWith(d.methodPrefix) && d.methodPrefix.length > bestLen) {
      best = ext; bestLen = d.methodPrefix.length;
    }
  }
  return best ?? 'core';
}

// Partition methods + notifications.
const coreMethods = {}, coreNotifs = {};
const extData = Object.fromEntries(Object.keys(EXT).map((k) => [k, { methods: {}, notifications: {}, errorCodes: {} }]));

for (const [name, m] of Object.entries(meta.methods)) {
  const dest = routeMethod(name);
  (dest === 'core' ? coreMethods : extData[dest].methods)[name] = m;
}
for (const [name, n] of Object.entries(meta.notifications)) {
  const dest = routeMethod(name);
  (dest === 'core' ? coreNotifs : extData[dest].notifications)[name] = n;
}
// Partition error-code groups.
const coreErrors = {};
for (const [group, codes] of Object.entries(meta.errorCodes)) {
  if (CORE_ERROR_GROUPS.includes(group)) { coreErrors[group] = codes; continue; }
  const owner = Object.entries(EXT).find(([, d]) => d.errorGroups.includes(group));
  if (!owner) throw new Error(`error group "${group}" not assigned to any extension`);
  extData[owner[0]].errorCodes[group] = codes;
}

// Write core.
mkdirSync(join(root, 'schema/core'), { recursive: true });
const core = {
  $schema: meta.$schema,
  title: meta.title + ' (Core)',
  description: 'Core machinery methods. Extensions live in schema/ext/<name>/manifest.json (docs/map-ext.md).',
  protocolVersion: meta.protocolVersion,
  methods: coreMethods,
  notifications: coreNotifs,
  errorCodes: coreErrors,
  tiers: meta.tiers,
};
writeFileSync(join(root, 'schema/core/meta.json'), JSON.stringify(core, null, 2) + '\n');

// Write per-extension manifests.
for (const [name, d] of Object.entries(EXT)) {
  const data = extData[name];
  const manifest = {
    name,
    uri: d.uri,
    version: '1.0.0',
    stability: d.stability,
    owner: d.owner,
    methodPrefix: d.methodPrefix,
    errorRange: d.errorRange,
    methods: data.methods,
    ...(Object.keys(data.notifications).length ? { notifications: data.notifications } : {}),
    ...(Object.keys(data.errorCodes).length ? { errorCodes: data.errorCodes } : {}),
  };
  mkdirSync(join(root, `schema/ext/${name}`), { recursive: true });
  writeFileSync(join(root, `schema/ext/${name}/manifest.json`), JSON.stringify(manifest, null, 2) + '\n');
}

// acp-tunnel: payload-protocol extension, no meta.json methods — authored directly.
const acp = {
  name: 'acp-tunnel',
  uri: 'urn:map:ext:acp-tunnel:1',
  version: '1.0.0',
  stability: 'staging',
  owner: 'multi-agent-protocol',
  payloadProtocol: 'acp',
  errorRange: null,
  methods: {},
  spec: '../../../docs/15-acp-tunnel-extension.md',
};
mkdirSync(join(root, 'schema/ext/acp-tunnel'), { recursive: true });
writeFileSync(join(root, 'schema/ext/acp-tunnel/manifest.json'), JSON.stringify(acp, null, 2) + '\n');

// identity: capability-only extension.
const identity = {
  name: 'identity',
  uri: 'urn:map:ext:identity:1',
  version: '1.0.0',
  stability: 'staging',
  owner: 'multi-agent-protocol',
  namespace: 'capability-only',
  errorRange: null,
  methods: {},
  note: 'persistentId stays opaque-in-core; this ext is the IdentityVerifier hook + DID/SPIFFE capability.',
};
mkdirSync(join(root, 'schema/ext/identity'), { recursive: true });
writeFileSync(join(root, 'schema/ext/identity/manifest.json'), JSON.stringify(identity, null, 2) + '\n');

const counts = Object.fromEntries(Object.entries(extData).map(([k, v]) => [k, Object.keys(v.methods).length]));
console.log('core methods:', Object.keys(coreMethods).length);
console.log('ext method counts:', counts);
console.log('wrote schema/core/meta.json + schema/ext/{', Object.keys(EXT).join(','), ',acp-tunnel,identity}/manifest.json');
